# Site settings
title: "E M I L"
description: "P O R T F O L I O"
baseurl: "" 
url: "https://knugen.github.io" 
author: "Your Name"

# Collection settings
collections:
  photos:
    output: true

# Social settings (Leave blank for that ultra-clean look)
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
theme: jekyll-theme-lens
